[package]
name = "wasm-rust"
version = "0.1.0"
authors = ["zplusfour <mail@zplusfour.is-a.dev>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"